services:
  frontend_hdyt:
    image: "${ECR_CLIENT_URL}:${BRANCH}-${SHA}"
    container_name: frontend_${BRANCH}_hdyt
    working_dir: /app
    ports:
      - "5573:8080"
    env_file:
      - .env

  backend_hdyt:
    image: "${ECR_SERVER_URL}:${BRANCH}-${SHA}"
    container_name: backend_${BRANCH}_hdyt
    working_dir: /run
    ports:
      - "${BACKEND_PORT}:3001"
    env_file:
      - .env
