name: CD Phase Dev

on:
  workflow_call:

jobs:
  build_dev:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    steps:
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Check Docker version
        run: docker --version

      - name: Remote SSH to deploy
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.RUNNER_HOST }}
          username: ${{ secrets.RUNNER_USERNAME }}
          password: ${{ secrets.RUNNER_PASSWORD }}
          port: 22
          script: |
            whoami
            cd /etc/actions-runner/NCKH/NCKH_project/NCKH_project
            pwd
            mkdir -p ${{ env.BRANCH }}
            aws s3api get-object --bucket ${{ env.AWS_S3_BUCKET }} --key ${{ env.BRANCH }}/docker-compose.yml ${{ env.BRANCH }}/docker-compose.yml
            aws s3api get-object --bucket ${{ env.AWS_S3_BUCKET }} --key ${{ env.BRANCH }}/.env ${{ env.BRANCH }}/.env
            cd ${{ env.BRANCH }}
            docker compose up -d --build
